language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - curl -o shellcheck.sh https://raw.githubusercontent.com/ScriBt/ScriBt-Examples/master/shellcheck.sh
 - bash shellcheck.sh

matrix:
  fast_finish: true
